// CoinGecko coin IDs for crypto price/logo fetching
export const COINGECKO_MAP = {
    // Major coins
    BTC: 'bitcoin',
    ETH: 'ethereum',
    USDT: 'tether',
    USDC: 'usd-coin',
    BNB: 'binancecoin',
    SOL: 'solana',
    XRP: 'ripple',
    ADA: 'cardano',
    DOGE: 'dogecoin',
    DOT: 'polkadot',
    AVAX: 'avalanche-2',
    LINK: 'chainlink',
    LTC: 'litecoin',
    TRX: 'tron',
    SHIB: 'shiba-inu',
    MATIC: 'matic-network',
    UNI: 'uniswap',
    ATOM: 'cosmos',
    XLM: 'stellar',
    NEAR: 'near',
    APT: 'aptos',
    FIL: 'filecoin',
    ICP: 'internet-computer',
    ARB: 'arbitrum',
    OP: 'optimism',
    // User-requested coins
    TOSHI: 'toshi',
    BRETT: 'based-brett',
    TURBO: 'turbo',
    VIRTUAL: 'virtual-protocol',
    HBAR: 'hedera-hashgraph',
    // Additional popular cryptos
    PEPE: 'pepe',
    WIF: 'dogwifcoin',
    BONK: 'bonk',
    FLOKI: 'floki',
    JUP: 'jupiter-exchange-solana',
    PYTH: 'pyth-network',
    SEI: 'sei-network',
    SUI: 'sui',
    TON: 'the-open-network',
    RNDR: 'render-token',
    INJ: 'injective-protocol',
    TIA: 'celestia',
    ORDI: 'ordi',
    JTO: 'jito-governance-token',
    WLD: 'worldcoin-wld',
    ENA: 'ethena',
    ETHFI: 'ether-fi',
    STRK: 'starknet',
    MANTA: 'manta-network',
    BLUR: 'blur',
    GALA: 'gala',
    SAND: 'the-sandbox',
    MANA: 'decentraland',
    AXS: 'axie-infinity',
    APE: 'apecoin',
    CRV: 'curve-dao-token',
    AAVE: 'aave',
    COMP: 'compound-governance-token',
    SUSHI: 'sushi',
    SNX: 'havven',
    GMX: 'gmx',
    KAVA: 'kava',
    ROSE: 'oasis-network',
    MINA: 'mina-protocol',
    FLOW: 'flow',
    CHZ: 'chiliz',
    THETA: 'theta-token',
    ENS: 'ethereum-name-service',
    GRT: 'the-graph',
    LDO: 'lido-dao',
    MKR: 'maker',
    FET: 'fetch-ai',
    OCEAN: 'ocean-protocol',
    AGIX: 'singularitynet',
    ZEC: 'zcash',
    DASH: 'dash',
    KSM: 'kusama',
    GLMR: 'moonbeam',
    ALGO: 'algorand',
    VET: 'vechain',
    CAKE: 'pancakeswap-token',
    FTM: 'fantom',
    XTZ: 'tezos',
    XMR: 'monero',
    DAI: 'dai',
    STX: 'blockstack',
    RUNE: 'thorchain',
    WAVES: 'waves',
    ENJ: 'enjincoin',
    BAT: 'basic-attention-token',
    ZRX: '0x',
    LRC: 'loopring',
    BAND: 'band-protocol',
    RLC: 'iexec-rlc',
    CELR: 'celer-network',
    ANKR: 'ankr',
    CELO: 'celo',
    ZIL: 'zilliqa',
    HOT: 'holotoken',
    ICX: 'icon',
    ONT: 'ontology',
    QTUM: 'qtum',
    OMG: 'omisego',
    NEO: 'neo',
    IOTA: 'iota',
    NANO: 'nano',
    DCR: 'decred',
    XEC: 'ecash',
    EGLD: 'elrond-erd-2',
    DYDX: 'dydx-chain',
    KNC: 'kyber-network',
    '1INCH': '1inch',
    BAL: 'balancer',
    PAXG: 'pax-gold',
    BUSD: 'binance-usd',
  };
  
  export const NSE_STOCKS = [
    { symbol: 'SCOM', name: 'Safaricom Plc', exchange: 'NSE', currency: 'KES' },
    { symbol: 'EQTY', name: 'Equity Group Holdings', exchange: 'NSE', currency: 'KES' },
    { symbol: 'KCB', name: 'KCB Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'EABL', name: 'East African Breweries', exchange: 'NSE', currency: 'KES' },
    { symbol: 'SBIC', name: 'Standard Chartered Bank Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'BAMB', name: 'Bamburi Cement', exchange: 'NSE', currency: 'KES' },
    { symbol: 'BAT', name: 'British American Tobacco Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'NMG', name: 'Nation Media Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'UNGA', name: 'Unga Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'CIC', name: 'CIC Insurance Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'COOP', name: 'Co-operative Bank of Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'NCBA', name: 'NCBA Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'STANBIC', name: 'Stanbic Holdings', exchange: 'NSE', currency: 'KES' },
    { symbol: 'ABSA', name: 'Absa Bank Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'DTBK', name: 'Diamond Trust Bank Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'JUB', name: 'Jubilee Holdings', exchange: 'NSE', currency: 'KES' },
    { symbol: 'BRIT', name: 'Britam Holdings', exchange: 'NSE', currency: 'KES' },
    { symbol: 'TOTL', name: 'Total Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'SCAN', name: 'WPP Scangroup', exchange: 'NSE', currency: 'KES' },
    { symbol: 'WTK', name: 'Williamson Tea Kenya', exchange: 'NSE', currency: 'KES' },
    { symbol: 'SGL', name: 'Sasini', exchange: 'NSE', currency: 'KES' },
    { symbol: 'KENAIR', name: 'Kenya Airways', exchange: 'NSE', currency: 'KES' },
    { symbol: 'FTGH', name: 'FTGH', exchange: 'NSE', currency: 'KES' },
    { symbol: 'UCHMI', name: 'Uchumi Supermarkets', exchange: 'NSE', currency: 'KES' },
    { symbol: 'OCH', name: 'Olympia Capital Holdings', exchange: 'NSE', currency: 'KES' },
    { symbol: 'PORT', name: 'Centum Investment', exchange: 'NSE', currency: 'KES' },
    { symbol: 'NMG', name: 'Nation Media Group', exchange: 'NSE', currency: 'KES' },
    { symbol: 'LGTV', name: 'Longhorn Publishers', exchange: 'NSE', currency: 'KES' },
    { symbol: 'KEGN', name: 'KenGen', exchange: 'NSE', currency: 'KES' },
    { symbol: 'KUKZ', name: 'Kurwitu Ventures', exchange: 'NSE', currency: 'KES' },
    { symbol: 'HAFR', name: 'Home Africa', exchange: 'NSE', currency: 'KES' },
    { symbol: 'TCL', name: 'Trans-Century', exchange: 'NSE', currency: 'KES' },
    { symbol: 'CK', name: 'Carbacid Investments', exchange: 'NSE', currency: 'KES' },
    { symbol: 'UME', name: 'Umeshma Capital', exchange: 'NSE', currency: 'KES' },
  ];
  
  export const US_STOCKS = [
    { symbol: 'AAPL', name: 'Apple Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'GOOGL', name: 'Alphabet Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'AMZN', name: 'Amazon.com Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'TSLA', name: 'Tesla Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'META', name: 'Meta Platforms Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'JPM', name: 'JPMorgan Chase & Co', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'V', name: 'Visa Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'WMT', name: 'Walmart Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'PG', name: 'Procter & Gamble Co', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'MA', name: 'Mastercard Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'HD', name: 'Home Depot Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'KO', name: 'Coca-Cola Co', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'PEP', name: 'PepsiCo Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'DIS', name: 'Walt Disney Co', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'NFLX', name: 'Netflix Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'PYPL', name: 'PayPal Holdings', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'PFE', name: 'Pfizer Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'BAC', name: 'Bank of America', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'ABBV', name: 'AbbVie Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'CRM', name: 'Salesforce Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'ADBE', name: 'Adobe Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'COST', name: 'Costco Wholesale', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'AVGO', name: 'Broadcom Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'NKE', name: 'Nike Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'MCD', name: "McDonald's Corp", exchange: 'NYSE', currency: 'USD' },
    { symbol: 'CSCO', name: 'Cisco Systems', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'ACN', name: 'Accenture Plc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'TXN', name: 'Texas Instruments', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'QCOM', name: 'Qualcomm Inc', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'UBER', name: 'Uber Technologies', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'SHOP', name: 'Shopify Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'SQ', name: 'Block Inc', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'PLTR', name: 'Palantir Technologies', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'COIN', name: 'Coinbase Global', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'HOOD', name: 'Robinhood Markets', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'SOXL', name: 'Direxion Semiconductor Bull 3X', exchange: 'NYSE', currency: 'USD' },
    { symbol: 'SOFI', name: 'SoFi Technologies', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'RIVN', name: 'Rivian Automotive', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'LCID', name: 'Lucid Group', exchange: 'NASDAQ', currency: 'USD' },
    { symbol: 'PLUG', name: 'Plug Power Inc', exchange: 'NASDAQ', currency: 'USD' },
  ];
  
  export const CRYPTO = [
    ...Object.keys(COINGECKO_MAP).map(symbol => {
      const names = {
        BTC: 'Bitcoin', ETH: 'Ethereum', USDT: 'Tether', USDC: 'USD Coin',
        BNB: 'BNB', SOL: 'Solana', XRP: 'XRP', ADA: 'Cardano',
        DOGE: 'Dogecoin', DOT: 'Polkadot', AVAX: 'Avalanche', LINK: 'Chainlink',
        LTC: 'Litecoin', TRX: 'TRON', SHIB: 'Shiba Inu', MATIC: 'Polygon',
        UNI: 'Uniswap', ATOM: 'Cosmos', XLM: 'Stellar', NEAR: 'NEAR Protocol',
        APT: 'Aptos', FIL: 'Filecoin', ICP: 'Internet Computer', ARB: 'Arbitrum',
        OP: 'Optimism', TOSHI: 'Toshi', BRETT: 'Brett', TURBO: 'Turbo',
        VIRTUAL: 'Virtual Protocol', HBAR: 'Hedera', PEPE: 'Pepe', WIF: 'dogwifcoin',
        BONK: 'Bonk', FLOKI: 'Floki', JUP: 'Jupiter', PYTH: 'Pyth Network',
        SEI: 'Sei', SUI: 'Sui', TON: 'Toncoin', RNDR: 'Render',
        INJ: 'Injective', TIA: 'Celestia', ORDI: 'Ordinals', JTO: 'Jito',
        WLD: 'Worldcoin', ENA: 'Ethena', ETHFI: 'ether.fi', STRK: 'Starknet',
        MANTA: 'Manta Network', BLUR: 'Blur', GALA: 'Gala', SAND: 'The Sandbox',
        MANA: 'Decentraland', AXS: 'Axie Infinity', APE: 'ApeCoin', CRV: 'Curve DAO',
        AAVE: 'Aave', COMP: 'Compound', SUSHI: 'SushiSwap', SNX: 'Synthetix',
        GMX: 'GMX', KAVA: 'Kava', ROSE: 'Oasis Network', MINA: 'Mina Protocol',
        FLOW: 'Flow', CHZ: 'Chiliz', THETA: 'Theta Network', ENS: 'Ethereum Name Service',
        GRT: 'The Graph', LDO: 'Lido DAO Token', MKR: 'Maker', FET: 'Fetch.ai',
        OCEAN: 'Ocean Protocol', AGIX: 'SingularityNET', ZEC: 'Zcash', DASH: 'Dash',
        KSM: 'Kusama', GLMR: 'Moonbeam', ALGO: 'Algorand', VET: 'VeChain',
        CAKE: 'PancakeSwap', FTM: 'Fantom', XTZ: 'Tezos', XMR: 'Monero',
        DAI: 'Dai', STX: 'Stacks', RUNE: 'THORChain', WAVES: 'Waves',
        ENJ: 'Enjin Coin', BAT: 'Basic Attention', ZRX: '0x Protocol', LRC: 'Loopring',
        BAND: 'Band Protocol', RLC: 'iExec RLC', CELR: 'Celer Network', ANKR: 'Ankr',
        CELO: 'Celo', ZIL: 'Zilliqa', HOT: 'Holo', ICX: 'ICON',
        ONT: 'Ontology', QTUM: 'Qtum', OMG: 'OMG Network', NEO: 'NEO',
        IOTA: 'IOTA', NANO: 'Nano', DCR: 'Decred', XEC: 'eCash',
        EGLD: 'MultiversX', DYDX: 'dYdX', KNC: 'Kyber Network', '1INCH': '1inch',
        BAL: 'Balancer', PAXG: 'PAX Gold', BUSD: 'Binance USD',
      };
      return { symbol, name: names[symbol] || symbol, exchange: 'CRYPTO', currency: 'USD' };
    }),
  ];
  
  export const ALL_ASSETS = [
    ...NSE_STOCKS.map(a => ({ ...a, asset_type: 'stock' })),
    ...US_STOCKS.map(a => ({ ...a, asset_type: 'stock' })),
    ...CRYPTO.map(a => ({ ...a, asset_type: 'crypto' })),
  ];